name: Deployment (Container)
on:
  push:
    branches:
    - master
env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    services:
      mongodb-service:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: sami
          MONGO_INITDB_ROOT_PASSWORD: mypass
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb
      MONGODB_CLUSTER_ADDRESS: mongodb-service
      MONGODB_USERNAME: sami
      MONGODB_PASSWORD: mypass
      PORT: 8080
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT # requires MongoDB Atlas to accept requests from anywhere!
      - name: Run tests
        run: npm test


