name: first-workflow
on:
  push:
    branches:
    - master
    - dev
jobs:
  testing:
    env:
      MONGODB_CLUSTER_ADDRESS: cluster0.bysk2fi.mongodb.net
      MONGODB_USERNAME: sami
      MONGODB_PASSWORD: 1shBQul8qdiwKPe0
      MONGODB_DB_NAME: cluster0
      PORT: 8080
    runs-on: ubuntu-latest
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: cache dependencies
      id: dep-cache
      uses: actions/cache@v3
      with:
        path: node_module
        key: dep-key-${{hashFiles('**/package-lock.json')}}
    - name: install dependencies
      if: steps.dep-cache.outputs.cache-hit != 'true'
      run: npm ci
    - name: connect to db server
      run: npm start & npx wait-on http://127.0.0.1:${{env.PORT}}
    - name: test app
      run: echo "testing ..."
  deploying:
    needs: [testing]
    runs-on: ubuntu-latest
    steps:
    - name: echo info
      run: echo "deploying ..."    
