name: first-workflow
on:
  push:
    branches:
    - master
    - dev
jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb
      MONGODB_CLUSTER_ADDRESS: db-service
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: rootpw
      PORT: 8080
    services:
      db-service:
        image: mongo:latest
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: rootpw
    steps:
    - name: get code
      uses: actions/checkout@v4
    - name: cache dependencies
      id: dep-cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: dep-key-${{hashFiles('**/package-lock.json')}}
    - name: install dependencies
      if: steps.dep-cache.outputs.cache-hit != 'true'
      run: npm ci
    - name: connect to db server
      run: npm start & npx wait-on http://127.0.0.1:${{env.PORT}}
    - name: test app
      run: echo "testing ..."
  deploying:
    needs: [testing]
    runs-on: ubuntu-latest
    steps:
    - name: echo info
      run: echo "deploying ..."    
